"set smarttab
set paste

set showcmd " Display incomplete commands.
set showmode " Display the mode you're in.

set smartindent
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab

set colorcolumn=80

" color
if has('unix')
  syntax on
endif

set ruler
set number
set cursorline
set title
set hlsearch

" Remember cursor position
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

" Python-specific settings
" Wrapping and tabs.
au BufEnter,BufRead *.py set tw=78 ts=4 sw=4 sta et sts=4 ai
au BufEnter,BufRead *.py let python_highlight_all = 1

call plug#begin()
Plug 'vim-ruby/vim-ruby'
Plug 'tpope/vim-rails'
Plug 'pangloss/vim-javascript'
Plug 'klen/python-mode'
Plug 'davidhalter/jedi-vim'
Plug 'rust-lang/rust.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'altercation/solarized'
call plug#end()

set runtimepath^=~/.vim/bundle/ctrlp.vim " ctrlp

" jsx
let g:jsx_ext_required = 0

" js
let g:javascript_enable_domhtmlcss = 1
let g:javascript_plugin_flow = 1

" rust
au BufEnter,BufRead *.rs set tw=78 ts=4 sw=4 sta et sts=4 ai
let g:rustfmt_autosave = 1
