set ruler
set number
set title

set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
set paste
set runtimepath^=~/.vim/bundle/ctrlp.vim " ctrlp

set showcmd " Display incomplete commands.
set showmode " Display the mode you're in.

set smartindent

set colorcolumn=80

" Remember cursor position
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

" Python-specific settings
" Wrapping and tabs.
au BufEnter,BufRead *.py set tw=78 ts=4 sw=4 sta et sts=4 ai
au BufEnter,BufRead *.py let python_highlight_all = 1

call pathogen#infect()

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete
